---
# Metallb address pool
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: mpcluster-pool
  namespace: metallb
spec:
  addresses:
  - 192.168.67.100-192.168.67.200

---
# L2 configuration
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb
spec:
  ipAddressPools:
  - mpcluster-pool
